# Generated by Django 5.1 on 2024-08-20 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='khachhang',
            name='dienthoai',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
