# Generated by Django 5.1 on 2024-08-22 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0002_alter_khachhang_dienthoai'),
    ]

    operations = [
        migrations.AddField(
            model_name='donhang',
            name='xacnhandonhang',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='donhang',
            name='ngaygiaoden',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='donhang',
            name='ngaygiaotu',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='yeucaumuon',
            name='ngaytra',
            field=models.DateField(),
        ),
    ]
