# Generated by Django 5.1 on 2024-08-22 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0003_donhang_xacnhandonhang_alter_donhang_ngaygiaoden_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lichsumuon',
            name='ngaytra',
            field=models.DateField(),
        ),
    ]
