# Generated by Django 5.1 on 2024-08-26 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0004_alter_lichsumuon_ngaytra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='khuyenmai',
            name='loaikhuyenmai',
            field=models.CharField(choices=[('Mua', 'Mua'), ('Muon', 'Mượn'), ('All;', 'all')], max_length=10),
        ),
    ]
