# Generated by Django 5.1 on 2024-09-10 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0007_alter_khuyenmai_loaikhuyenmai'),
    ]

    operations = [
        migrations.AddField(
            model_name='khachhang',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatar/%Y/%m/'),
        ),
    ]
