# Generated by Django 5.1 on 2024-09-12 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0008_khachhang_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='khachhang',
            name='email_xac_thuc',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='khachhang',
            name='otp_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='khachhang',
            name='otp_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
