# Generated by Django 5.1 on 2024-09-12 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0009_khachhang_email_xac_thuc_khachhang_otp_attempts_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('otp', models.CharField(max_length=6)),
                ('otp_created_at', models.DateTimeField(auto_now_add=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('otp_attempts', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='khachhang',
            name='otp_attempts',
        ),
    ]
