# Generated by Django 5.1 on 2024-08-20 09:25

import ckeditor.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('bookapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoaiThongBao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngaytao', models.DateTimeField(auto_now_add=True)),
                ('ngaycapnhap', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('tieude', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ThongBao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngaytao', models.DateTimeField(auto_now_add=True)),
                ('ngaycapnhap', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('ngaythongbao', models.DateTimeField()),
                ('loinhan', ckeditor.fields.RichTextField()),
                ('group', models.ForeignKey(blank=True, help_text='Chọn nhóm khách hàng nhận thông báo', null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.group')),
                ('khachhang', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('loaithongbao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='notifications.loaithongbao')),
                ('sanpham', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bookapp.sanpham')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
